language: node_js
node_js:
- "6"
- "8"
- "10"
- "11"
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - DEPLOY="true"
        - MAIN="true"
    - os: linux
      dist: trusty
      env:
        - DEPLOY="true"
        - ARCH="armv7"
    - os: linux
      dist: trusty
      env:
        - DEPLOY="true"
        - ARCH="armv8"
    - os: linux
      dist: trusty
      env:
        - ELECTRON="3.0.0"
    - os: osx
      env:
        - DEPLOY="true"

env:
  global:
    - GH_REF: github.com/noahw3/zeromq.js
    - secure: HflE2vnYe6lFP7LQMIibN+Z/gTzcppazP4belSwyMYklN9jZGuzIqeGIbUYvAzn/+FksmpKaVpJsi3Di5LpGsf1kq2pEpNHKVgJhmYO9lxXq4/rOvRkgr/SQ+3e6qIQ91u6Zrmt5a5+DuNyBOOvw+eLZVO4avMP2DpJjy/z8COIcl8zBKRJd+bjbz8fq0c3K3KnuoJLdCQfYBc7lIoghZJ9r++SmGQeVnGSJlqrG4zhodB/QAvIo2PaQyBzvpJxPN3E+KKZDMNh2mk0+KC4mbbCZlcwlWbKpIVcrosQsC20lrsqFQvRH/jQi7PV6JKkZYjys/zrYHjzCnc3cZzIy7Wck4k99GllIj5Q/SXyxmnWd1smsnlavitHGg1Ess+wkVkPfnlum01rO4pABG+W4YSssEU82jsFU5MNnu3vn29+e5iquh2kyKRyDlEYss4SFB5CqFis4cOW4lbLy6BSGZyhNRgTynSbnOb7y7WhG2RAD7PLn0FlxLor1pG5bx7JotfUAteTgBSZSP+Ec0Uf171qt24PsuZwBQEH2uNdzY1kCKUiQbS9o1Q03naTtpjiuERNNl8IZRZN9vN3hnyCohyYvz0JMOHtT+dypDMfDGovhbHBROk8eSaaut6CFW5lbTJMheM7xgUnudzEizsTKBip7V81vQWY7YDwKFM9n33c=

before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - if [ -n "$ELECTRON" ]; then npm install electron@${ELECTRON}; fi

install:
  - if [ -n "$ARCH" ]; then bash ./scripts/cross_compile.sh ${ARCH}; fi
  - if [ -n "$ELECTRON" ]; then npm install --runtime=electron --target=${ELECTRON} --disturl=https://atom.io/download/electron; fi
  - if [ -z "$ARCH" ] && [ -z "$ELECTRON" ]; then npm install; fi

script:
  - if [ -n "$ELECTRON" ]; then travis_retry npm run test:electron; fi
  - if [ -z "$ARCH" ] && [ -z "$ELECTRON" ]; then travis_retry npm run coverage; fi

after_success:
  - if [ "$MAIN" = "true" ]; then bash <(curl -s https://codecov.io/bash); fi
  - if [ "$MAIN" = "true" ]; then bash ./scripts/publish_docs.sh; fi

deploy:
  provider: script
  skip_cleanup: true
  script:
    - if [ -z "$ARCH" ]; then ./node_modules/prebuild/bin.js --all --strip -u ${GH_TOKEN}; else bash ./scripts/cross_compile.sh ${ARCH} ${GH_TOKEN}; fi
  on:
    condition: $DEPLOY = "true"
    tags: true

# notifications:
#   slack:
#     secure: nklWvK1Mvoj5zly8PO0WmgQdakaSa5Ixwbxw4+1yyIKgyEUbyHzu0oySMAuyMPPV3nLaTaB/bwFxvrsUP6lxoO1CvQMUTrucLm3H5FXDDuTBBw5/tREFyuUy6XPeVsTPdL9ltrvCn8mTBYNZOM/3BWq6mV0XDHpxAIgE3FA2AUTrNoAxLqXC/V7ZmTnDYuH2T/cdeyP+Ri0UDuszUn/dzTM/fOSVpJ/J74JylJ5FH7x5z9lnD6T/916t8//i4tzoEaFkS4V7QgAj0Bta8BEMP0BN40Wap9UgXfrzafCnHDjcbKRoyVEs09kWMbrdY572EGiow2B+QOlYELLYCcD00VH71zDCpw1Ji6di3v+CxCzxFcNyZz8i/Hb8PIfYTyHV2C43X/doVzC3MVllw+d3IVTR0smn2jwjhr+szm9MDQcnUxq5zuOCiAMzE51hbhLQATUNQIiqsD0X+NK3o5urb/Fjb6I6q3MO7GJkuvsda1ni5OEPeFAlYKjvgBiwUZnc32uBHfd3iGzbdwzihSKreuIdVTCtmlnhVmM0ztg5E+BQ8SxWJPxLw5c+9ZaEja5bVCkZF4L3P/EcsdBQ1YmorsROgf/p+PsrnqKAy9zU/NynQQYODx28IPcuQgJbhzeTUEINnFej513BRnkREgjLY5bjXY6iLjKdlRo8kPVqrj8=
